### ISSUE TITLE
Interfaces

### ISSUE THREAD

**Issue by edurevsky** [gustavofreze/kotlin4noobs#13]
Ainda não existe um roadmap abordando as Interfaces, algo que faz sentido ter pois faz parte do paradigma OO e Kotlin suporta esse paradigma.
Seria interessante para quem está vendo o repositório ter um breve contato sobre como criar Interfaces, herdar Interfaces, implementar Interfaces com métodos default e também dar um exemplo do uso da Delegação de Interface.
A utilidade do roadmap estaria na questão do polimorfismo, algo que foi pouco explorado durante o roadmap.

**Comment by gustavofreze** [comment]
[Adicionado](https://github.com/gustavofreze/kotlin4noobs/commit/e2b2fdf73bec625fa5d978108480aa9ece6857ed).
