### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Suburbanno** [gustavofreze/kotlin4noobs#66]
Olá!

Muito obrigado pelo projeto, você poderia informar a ordem de estudo? qual a linha de tópicos seguir?

[Funções](https://github.com/gustavofreze/kotlin4noobs/blob/main/doc/readmes/roadmap/FUNCTIONS.md)
[Variáveis](https://github.com/gustavofreze/kotlin4noobs/blob/main/doc/readmes/roadmap/VARIABLES.md)
[Tipos de dados](https://github.com/gustavofreze/kotlin4noobs/blob/main/doc/readmes/roadmap/TYPES.md)
[Loops](https://github.com/gustavofreze/kotlin4noobs/blob/main/doc/readmes/roadmap/LOOPS.md)
[Classes e objetos](https://github.com/gustavofreze/kotlin4noobs/blob/main/doc/readmes/roadmap/CLASS.md)
[Expressões condicionais](https://github.com/gustavofreze/kotlin4noobs/blob/main/doc/readmes/roadmap/EXPRESSIONS.md)
[Exceções](https://github.com/gustavofreze/kotlin4noobs/blob/main/doc/readmes/roadmap/EXCEPTIONS.md)
[Corrotinas](https://github.com/gustavofreze/kotlin4noobs/blob/main/doc/readmes/roadmap/COROUTINES.md)
[Convenções de codificação](https://github.com/gustavofreze/kotlin4noobs/blob/main/doc/readmes/roadmap/CONVENTIONS.md)

@gustavofreze

**Comment by gustavofreze** [comment]
Olá @Suburbanno. A ordem é exatamente essa disposta no **Roadmap**, no tópico **A linguagem**. Ou seja, você vai iniciar por [Funções](https://github.com/gustavofreze/kotlin4noobs/blob/main/doc/readmes/roadmap/FUNCTIONS.md).

**Comment by Suburbanno** [comment]
> Olá @Suburbanno. A ordem é exatamente essa disposta no **Roadmap**, no tópico **A linguagem**. Ou seja, você vai iniciar por [Funções](https://github.com/gustavofreze/kotlin4noobs/blob/main/doc/readmes/roadmap/FUNCTIONS.md).

Obrigado, perguntei pois geralmente em outros cursos/roadmaps variveis, tipos aparecem no inicio da lista.
